### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by KatieMFritz** [comment]
### No hosted site

Looking forward to reviewing this, but there's no hosted site yet! 😬 

I'm not seeing a `gh-pages` branch in your repository either. Did you type `git push origin master:gh-pages` in your terminal? Did you get any error messages?

Don't forget to check your links before you submit in the future! ✔️

**Comment by levinsonmm** [comment]
Whoops! I forgot the gh-pages part. Thanks!

**Comment by KatieMFritz** [comment]
LOL at Curious George and banana science! 🍌 

This looks really good. Nice indentation, too! :shipit:

**Comment by KatieMFritz** [comment]
By the way, nice job on your commit messages. Specific commit messages will help you a lot down the road. 😄

**Comment by levinsonmm** [comment]
Thank you!
